name: Cache VCPKG

on: workflow_dispatch

jobs:
  cache:
    runs-on: windows-latest
    steps:
    - name: Install socket-io-client (vcpkg)
      if: ${{ steps.cache-vcpkg.outputs.cache-hit != 'true' }}
      run: |
        vcpkg install socket-io-client:x64-windows
        vcpkg integrate install
    - uses: actions/cache/save@v3
      id: cache-vcpkg
      with:
        path: C:/vcpkg
        key: ${{ runner.os }}-vcpkg
